export const Texts = {
    email: 'email',
    password: 'password',
    login: 'login',
    signUp: 'signUp',
    username: 'username',
    settings: 'settings',
    colorTheme: 'colorTheme',
    dark: 'dark',
    light: 'light',
    language: 'language',
    English: 'english',
    Turkish: 'turkish',
    signOut: 'signOut',
};

export const English = {
    [Texts.email]: 'E-mail',
    [Texts.password]: 'Password',
    [Texts.login]: 'Login',
    [Texts.signUp]: 'Sign Up',
    [Texts.username]: 'Username',
    [Texts.settings]: 'Settings',
    [Texts.colorTheme]: 'Color Theme',
    [Texts.dark]: 'Dark',
    [Texts.light]: 'Light',
    [Texts.language]: 'Language',
    [Texts.English]: 'English',
    [Texts.Turkish]: 'Türkçe',
    [Texts.signOut]: 'Sign Out',
};

export const Turkish = {
    [Texts.email]: 'E-posta',
    [Texts.password]: 'Şifre',
    [Texts.login]: 'Giriş Yap',
    [Texts.signUp]: 'Kayıt Ol',
    [Texts.username]: 'Kullanıcı Adı',
    [Texts.settings]: 'Ayarlar',
    [Texts.colorTheme]: 'Renk Teması',
    [Texts.dark]: 'Karanlık',
    [Texts.light]: 'Aydınlık',
    [Texts.language]: 'Dil',
    [Texts.English]: 'English',
    [Texts.Turkish]: 'Türkçe',
    [Texts.signOut]: 'Çıkış Yap',
}
